export const MAP_NODES = [
    {
        id: 'teranvil',
        name: 'Теранвиль',
        type: 'City',
        faction: 'Forest Alliance',
        danger: 'Low',
        access: 'Friendly',
        recommendedLevel: 3,
        description: 'Эльфийский город на границе древнего леса. Здесь доступны торговля и квесты.',
        tooltip: 'City: Teranvil',
        x: 62,
        y: 18,
        actions: [
            { id: 'enter', label: 'Enter City', kind: 'enter' },
            { id: 'trade', label: 'Trade', kind: 'trade' },
            { id: 'talk', label: 'Talk', kind: 'talk' },
            { id: 'scout', label: 'Scout', kind: 'scout' },
        ],
    },
    {
        id: 'gurlok',
        name: 'Урлок',
        type: 'Stronghold',
        faction: 'Ash Legion',
        danger: 'High',
        access: 'Hostile',
        recommendedLevel: 8,
        description: 'Крепость на огненных склонах. Частые вражеские патрули и рейды.',
        tooltip: 'Stronghold: Gurlok',
        x: 84,
        y: 27,
        actions: [
            { id: 'scout', label: 'Scout Enemy', kind: 'scout' },
            { id: 'battle', label: 'Enter Battle', kind: 'combat' },
            { id: 'retreat', label: 'Retreat', kind: 'rest' },
        ],
    },
    {
        id: 'tartrim',
        name: 'Тартрим',
        type: 'City',
        faction: 'Stone Crown',
        danger: 'Medium',
        access: 'Neutral',
        recommendedLevel: 5,
        description: 'Город у горного перевала. Здесь часто выдают миссии проводников.',
        tooltip: 'City: Tartrim',
        x: 40,
        y: 32,
        actions: [
            { id: 'travel', label: 'Travel', kind: 'travel' },
            { id: 'quest', label: 'Accept Quest', kind: 'quest' },
            { id: 'talk', label: 'Talk', kind: 'talk' },
        ],
    },
    {
        id: 'feldan',
        name: 'Фелдан',
        type: 'City',
        faction: 'Stone Crown',
        danger: 'Medium',
        access: 'Neutral',
        recommendedLevel: 6,
        description: 'Торговая точка между реками и перевалами, удобный транзитный узел.',
        tooltip: 'City: Feldan',
        x: 52,
        y: 46,
        actions: [
            { id: 'enter', label: 'Enter City', kind: 'enter' },
            { id: 'trade', label: 'Trade', kind: 'trade' },
            { id: 'rest', label: 'Rest', kind: 'rest' },
        ],
    },
    {
        id: 'bromkar',
        name: 'Бром-кар',
        type: 'Fortress',
        faction: 'Stone Crown',
        danger: 'High',
        access: 'Neutral',
        recommendedLevel: 7,
        description: 'Старая крепость со спорной территорией вокруг. Есть шанс внезапного боя.',
        tooltip: 'Fortress: Brom-kar',
        x: 45,
        y: 58,
        actions: [
            { id: 'scout', label: 'Scout', kind: 'scout' },
            { id: 'battle', label: 'Join Battle', kind: 'combat' },
        ],
    },
    {
        id: 'breinkhold',
        name: 'Брейнхольд',
        type: 'City',
        faction: 'Trade League',
        danger: 'Low',
        access: 'Friendly',
        recommendedLevel: 4,
        description: 'Безопасный торговый город. Много ремесленников и редких материалов.',
        tooltip: 'City: Breinkhold',
        x: 51,
        y: 72,
        actions: [
            { id: 'trade', label: 'Trade', kind: 'trade' },
            { id: 'quest', label: 'Accept Quest', kind: 'quest' },
            { id: 'travel', label: 'Travel', kind: 'travel' },
        ],
    },
    {
        id: 'arklein',
        name: 'Арклейн',
        type: 'Town',
        faction: 'Trade League',
        danger: 'Medium',
        access: 'Friendly',
        recommendedLevel: 5,
        description: 'Пограничный город с активными заданиями на охоту и патрулирование.',
        tooltip: 'Town: Arklein',
        x: 64,
        y: 71,
        actions: [
            { id: 'quest', label: 'Accept Quest', kind: 'quest' },
            { id: 'talk', label: 'Talk', kind: 'talk' },
            { id: 'scout', label: 'Scout', kind: 'scout' },
        ],
    },
    {
        id: 'grankor',
        name: 'Гранкор',
        type: 'Citadel',
        faction: 'Ash Legion',
        danger: 'High',
        access: 'Hostile',
        recommendedLevel: 9,
        description: 'Цитадель в каменных каньонах. Высокий риск, но хорошие награды.',
        tooltip: 'Citadel: Grankor',
        x: 74,
        y: 79,
        actions: [
            { id: 'battle', label: 'Enter Battle', kind: 'combat' },
            { id: 'scout', label: 'Scout Enemy', kind: 'scout' },
            { id: 'retreat', label: 'Retreat', kind: 'rest' },
        ],
    },
];
