import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
export function PlayerQuickPanel(props) {
    const { name, avatarLetter, hpText, mpText, staminaText, activeStats, equipment, inventory, quickActions, resolveItemById, resolveItemImage } = props;
    return (_jsxs("aside", { className: "wm-left card", children: [_jsx("h3", { children: "\u0420\u045F\u0420\u00B5\u0421\u0402\u0421\u0403\u0420\u0455\u0420\u0405\u0420\u00B0\u0420\u00B6" }), _jsxs("div", { className: "wm-avatar-wrap", title: `${name} status`, children: [_jsx("button", { className: "wm-avatar", title: `Name: ${name}`, children: avatarLetter }), _jsxs("div", { className: "wm-orbs", children: [_jsxs("span", { children: [_jsx("i", { className: "wm-orb hp" }), hpText] }), _jsxs("span", { children: [_jsx("i", { className: "wm-orb mp" }), mpText] }), _jsxs("span", { children: [_jsx("i", { className: "wm-orb sta" }), staminaText] })] }), _jsx("div", { className: "wm-quick-actions", children: quickActions.map((action) => (_jsxs("button", { className: `wm-quick-btn ${action.tone}`, onClick: action.onClick, title: action.title, children: [_jsx("span", { children: action.icon }), action.badge ? _jsx("b", { children: action.badge }) : null] }, action.id))) })] }), _jsxs("div", { className: "wm-mini-stats", children: [_jsxs("span", { className: "gold", children: ["\u0440\u045F\u0404\u2122 ", inventory.gold] }), _jsxs("span", { children: ["\u0432\u0459\u201D ", activeStats.strength] }), _jsxs("span", { children: ["\u0440\u045F\u203A\u040E ", activeStats.constitution] }), _jsxs("span", { children: ["\u0440\u045F\u040B\u0407 ", activeStats.perception] }), _jsxs("span", { children: ["\u0440\u045F\u00A7\u00A0 ", activeStats.intelligence] }), _jsxs("span", { children: ["\u0432\u0098\u0098 ", activeStats.luck] })] }), _jsx("div", { className: "wm-equipment", children: Object.entries(equipment).map(([slot, itemId]) => (_jsxs("div", { className: "wm-equip-row", children: [_jsx("span", { children: slot }), _jsx("strong", { children: itemId ? (resolveItemById?.(itemId)?.name ?? itemId) : 'Empty' })] }, slot))) }), _jsx("h3", { children: "\u0420\u0098\u0420\u0405\u0420\u0406\u0420\u00B5\u0420\u0405\u0421\u201A\u0420\u00B0\u0421\u0402\u0421\u040A" }), _jsx("div", { className: "wm-inventory-grid", children: inventory.items.slice(0, 16).map((entry) => {
                    const item = resolveItemById?.(entry.itemId) ?? null;
                    const image = resolveItemImage?.(item);
                    return (_jsxs("div", { className: "wm-item-cell", title: item?.name ?? entry.itemId, children: [_jsx("span", { className: `wm-item-cell-icon${image ? ' has-image' : ''}`, style: image ? {
                                    backgroundImage: `url("${image}")`,
                                    backgroundSize: 'contain',
                                    backgroundRepeat: 'no-repeat',
                                    backgroundPosition: 'center',
                                } : undefined, children: !image ? (item?.name.slice(0, 2).toUpperCase() ?? entry.itemId.slice(0, 2).toUpperCase()) : null }), _jsx("small", { children: entry.quantity })] }, entry.itemId));
                }) })] }));
}
