import { ZONE_COLORS } from './zoneColors';
import type { WorldMapZone, ZoneType } from './zoneEditorTypes';

const BASE_TIMESTAMP = 1_713_484_800_000;

function circleZone(zone: Omit<WorldMapZone, 'shape' | 'createdAt' | 'updatedAt'> & { x: number; y: number; radius: number }): WorldMapZone {
  return {
    ...zone,
    shape: 'circle',
    createdAt: BASE_TIMESTAMP,
    updatedAt: BASE_TIMESTAMP,
  };
}

export type Zone = WorldMapZone;
export type { ZoneType };
export { ZONE_COLORS };

export const WORLD_MAP_ZONES: WorldMapZone[] = [
  circleZone({
    id: 'arklein',
    name: 'Арклейн',
    type: 'city',
    x: 0.56,
    y: 0.86,
    radius: 0.05,
    description: 'Пограничный город',
    tooltip: 'Пограничный город Арклейн',
    dangerLevel: 1,
    recommendedLevel: 1,
    targetScene: 'city_arklein',
    isDiscovered: true,
    isVisibleToPlayer: true,
    isSafeZone: true,
    allowPvP: false,
    faction: 'Арклейн',
    region: 'Южная граница',
  }),
  circleZone({
    id: 'trader_outpost',
    name: 'Торговый пост Кленовой Долины',
    type: 'settlement',
    x: 0.45,
    y: 0.69,
    radius: 0.04,
    description: 'Небольшой лагерь с ремесленниками и караванами.',
    tooltip: 'Небольшой торговый пост',
    dangerLevel: 1,
    recommendedLevel: 1,
    isDiscovered: true,
    isVisibleToPlayer: true,
    isSafeZone: true,
    allowPvP: false,
    region: 'Кленовая Долина',
  }),
  circleZone({
    id: 'ember_forges',
    name: 'Огненные Жерла',
    type: 'grind',
    x: 0.69,
    y: 0.62,
    radius: 0.05,
    description: 'Опасные лавовые карманы. Отличная зона для прокачки.',
    tooltip: 'Горячая grind-зона',
    dangerLevel: 5,
    recommendedLevel: 5,
    requiredLevel: 4,
    isDiscovered: true,
    isVisibleToPlayer: true,
    allowPvP: true,
    enemyTableId: 'ember_forges_enemies',
    region: 'Лавовые Жерла',
  }),
  circleZone({
    id: 'ashwood_grove',
    name: 'Пепельная Роща',
    type: 'resource',
    x: 0.36,
    y: 0.47,
    radius: 0.045,
    description: 'Редкие травы и магическая древесина. Ресурсная зона.',
    tooltip: 'Сбор редких ресурсов',
    dangerLevel: 2,
    recommendedLevel: 2,
    isDiscovered: true,
    isVisibleToPlayer: true,
    resourceTableId: 'ashwood_resources',
    region: 'Пепельная Роща',
  }),
  circleZone({
    id: 'guild_camp',
    name: 'Лагерь Наставников',
    type: 'profession',
    x: 0.62,
    y: 0.45,
    radius: 0.04,
    description: 'Тут обучают боевым профессиям и базовым специализациям.',
    tooltip: 'Профессии и наставники',
    dangerLevel: 1,
    recommendedLevel: 1,
    isDiscovered: true,
    isVisibleToPlayer: true,
    professionId: 'combat_mastery',
    region: 'Лагерь Наставников',
  }),
  circleZone({
    id: 'old_bridge',
    name: 'Старый Мост',
    type: 'safe',
    x: 0.52,
    y: 0.56,
    radius: 0.035,
    description: 'Безопасная нейтральная территория. PvP запрещен.',
    tooltip: 'Безопасная территория',
    dangerLevel: 0,
    recommendedLevel: 1,
    isDiscovered: true,
    isVisibleToPlayer: true,
    isSafeZone: true,
    allowPvP: false,
    region: 'Старый Мост',
  }),
  circleZone({
    id: 'ruined_hall',
    name: 'Руины Стихийного Зала',
    type: 'dungeon',
    x: 0.79,
    y: 0.35,
    radius: 0.05,
    description: 'Подземелье для группового прохождения.',
    tooltip: 'Подземелье высокой опасности',
    dangerLevel: 6,
    recommendedLevel: 6,
    requiredLevel: 6,
    isDiscovered: true,
    isVisibleToPlayer: true,
    allowPvP: false,
    enemyTableId: 'ruined_hall_enemies',
    region: 'Северные руины',
  }),
];
