"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.SummonControlType = exports.SummonType = exports.SpiritType = exports.RiskSeverity = exports.SkillRiskType = exports.SkillClassRole = exports.AcquisitionType = exports.StatType = exports.CastType = exports.SkillAreaShape = exports.SkillTargetType = exports.EffectStackMode = exports.EffectType = exports.HealType = exports.MagicSchoolType = exports.ElementType = exports.PhysicalDamageType = exports.DamageKind = exports.SkillResourceType = exports.SkillSubtype = exports.SkillType = void 0;
var SkillType;
(function (SkillType) {
    SkillType["PHYSICAL"] = "physical";
    SkillType["MAGIC"] = "magic";
    SkillType["ELEMENTAL_MAGIC"] = "elemental_magic";
    SkillType["NORMAL_MAGIC"] = "normal_magic";
    SkillType["FORBIDDEN_MAGIC"] = "forbidden_magic";
    SkillType["SHAMANISM"] = "shamanism";
    SkillType["RUNE"] = "rune";
    SkillType["MIXED"] = "mixed";
    SkillType["PASSIVE"] = "passive";
})(SkillType || (exports.SkillType = SkillType = {}));
var SkillSubtype;
(function (SkillSubtype) {
    SkillSubtype["MELEE"] = "melee";
    SkillSubtype["RANGED"] = "ranged";
    SkillSubtype["SPELL"] = "spell";
    SkillSubtype["CHANT"] = "chant";
    SkillSubtype["RITUAL"] = "ritual";
    SkillSubtype["TOTEM"] = "totem";
    SkillSubtype["CONTRACT"] = "contract";
    SkillSubtype["CURSE"] = "curse";
    SkillSubtype["BLESSING"] = "blessing";
    SkillSubtype["HEAL"] = "heal";
    SkillSubtype["SUMMON"] = "summon";
    SkillSubtype["TRANSFORMATION"] = "transformation";
    SkillSubtype["CONTROL"] = "control";
    SkillSubtype["AURA"] = "aura";
    SkillSubtype["RUNE_MARK"] = "rune_mark";
    SkillSubtype["WEAPON_TECHNIQUE"] = "weapon_technique";
})(SkillSubtype || (exports.SkillSubtype = SkillSubtype = {}));
var SkillResourceType;
(function (SkillResourceType) {
    SkillResourceType["MP"] = "mp";
    SkillResourceType["STAMINA"] = "stamina";
    SkillResourceType["HP"] = "hp";
    SkillResourceType["BLOOD"] = "blood";
    SkillResourceType["MEMORY"] = "memory";
    SkillResourceType["SOUL"] = "soul";
    SkillResourceType["RUNE_CHARGE"] = "rune_charge";
    SkillResourceType["SPIRIT_FAVOR"] = "spirit_favor";
    SkillResourceType["ITEM"] = "item";
})(SkillResourceType || (exports.SkillResourceType = SkillResourceType = {}));
var DamageKind;
(function (DamageKind) {
    DamageKind["PHYSICAL"] = "physical";
    DamageKind["ELEMENTAL"] = "elemental";
    DamageKind["MAGIC"] = "magic";
    DamageKind["SPIRITUAL"] = "spiritual";
    DamageKind["RUNE"] = "rune";
    DamageKind["FORBIDDEN"] = "forbidden";
    DamageKind["TRUE"] = "true";
})(DamageKind || (exports.DamageKind = DamageKind = {}));
var PhysicalDamageType;
(function (PhysicalDamageType) {
    PhysicalDamageType["SLASHING"] = "slashing";
    PhysicalDamageType["PIERCING"] = "piercing";
    PhysicalDamageType["BLUNT"] = "blunt";
})(PhysicalDamageType || (exports.PhysicalDamageType = PhysicalDamageType = {}));
var ElementType;
(function (ElementType) {
    ElementType["FIRE"] = "fire";
    ElementType["WATER"] = "water";
    ElementType["EARTH"] = "earth";
    ElementType["AIR"] = "air";
    ElementType["LIGHT"] = "light";
    ElementType["DARKNESS"] = "darkness";
})(ElementType || (exports.ElementType = ElementType = {}));
var MagicSchoolType;
(function (MagicSchoolType) {
    MagicSchoolType["ELEMENTAL"] = "elemental";
    MagicSchoolType["NORMAL"] = "normal";
    MagicSchoolType["LIFE"] = "life";
    MagicSchoolType["DEATH"] = "death";
    MagicSchoolType["BLOOD"] = "blood";
    MagicSchoolType["MIND"] = "mind";
    MagicSchoolType["SHADOW"] = "shadow";
    MagicSchoolType["ILLUSION"] = "illusion";
    MagicSchoolType["NECROMANCY"] = "necromancy";
    MagicSchoolType["FORBIDDEN"] = "forbidden";
})(MagicSchoolType || (exports.MagicSchoolType = MagicSchoolType = {}));
var HealType;
(function (HealType) {
    HealType["DIRECT"] = "direct";
    HealType["OVER_TIME"] = "over_time";
    HealType["CLEANSE"] = "cleanse";
    HealType["SHIELD"] = "shield";
    HealType["LIFE_STEAL"] = "life_steal";
})(HealType || (exports.HealType = HealType = {}));
var EffectType;
(function (EffectType) {
    EffectType["BURN"] = "burn";
    EffectType["BLEED"] = "bleed";
    EffectType["POISON"] = "poison";
    EffectType["CURSE"] = "curse";
    EffectType["STUN"] = "stun";
    EffectType["KNOCKDOWN"] = "knockdown";
    EffectType["ROOT"] = "root";
    EffectType["SLOW"] = "slow";
    EffectType["SILENCE"] = "silence";
    EffectType["FEAR"] = "fear";
    EffectType["CONFUSION"] = "confusion";
    EffectType["BLIND"] = "blind";
    EffectType["WEAKNESS"] = "weakness";
    EffectType["ARMOR_BREAK"] = "armor_break";
    EffectType["RESISTANCE_BREAK"] = "resistance_break";
    EffectType["CRIT_CHANCE_BUFF"] = "crit_chance_buff";
    EffectType["DAMAGE_BUFF"] = "damage_buff";
    EffectType["DEFENSE_BUFF"] = "defense_buff";
    EffectType["DODGE_BUFF"] = "dodge_buff";
    EffectType["HEAL_OVER_TIME"] = "heal_over_time";
    EffectType["SHIELD"] = "shield";
    EffectType["TRANSFORM"] = "transform";
    EffectType["MANA_BURN"] = "mana_burn";
    EffectType["STAMINA_DRAIN"] = "stamina_drain";
})(EffectType || (exports.EffectType = EffectType = {}));
var EffectStackMode;
(function (EffectStackMode) {
    EffectStackMode["REFRESH"] = "refresh";
    EffectStackMode["STACK"] = "stack";
    EffectStackMode["REPLACE"] = "replace";
    EffectStackMode["IGNORE"] = "ignore";
})(EffectStackMode || (exports.EffectStackMode = EffectStackMode = {}));
var SkillTargetType;
(function (SkillTargetType) {
    SkillTargetType["SELF"] = "self";
    SkillTargetType["SINGLE_ALLY"] = "single_ally";
    SkillTargetType["SINGLE_ENEMY"] = "single_enemy";
    SkillTargetType["ANY_SINGLE"] = "any_single";
    SkillTargetType["ALL_ALLIES"] = "all_allies";
    SkillTargetType["ALL_ENEMIES"] = "all_enemies";
    SkillTargetType["AREA"] = "area";
    SkillTargetType["CONE"] = "cone";
    SkillTargetType["LINE"] = "line";
    SkillTargetType["GLOBAL"] = "global";
})(SkillTargetType || (exports.SkillTargetType = SkillTargetType = {}));
var SkillAreaShape;
(function (SkillAreaShape) {
    SkillAreaShape["CIRCLE"] = "circle";
    SkillAreaShape["CONE"] = "cone";
    SkillAreaShape["LINE"] = "line";
    SkillAreaShape["RING"] = "ring";
    SkillAreaShape["FIELD"] = "field";
})(SkillAreaShape || (exports.SkillAreaShape = SkillAreaShape = {}));
var CastType;
(function (CastType) {
    CastType["INSTANT"] = "instant";
    CastType["CAST_TIME"] = "cast_time";
    CastType["CHANNELING"] = "channeling";
    CastType["RITUAL"] = "ritual";
    CastType["TOGGLE"] = "toggle";
})(CastType || (exports.CastType = CastType = {}));
var StatType;
(function (StatType) {
    StatType["HP"] = "hp";
    StatType["MP"] = "mp";
    StatType["STAMINA"] = "stamina";
    StatType["STRENGTH"] = "strength";
    StatType["CONSTITUTION"] = "constitution";
    StatType["DEXTERITY"] = "dexterity";
    StatType["INTELLIGENCE"] = "intelligence";
    StatType["LUCK"] = "luck";
    StatType["PERCEPTION"] = "perception";
    StatType["WILLPOWER"] = "willpower";
})(StatType || (exports.StatType = StatType = {}));
var AcquisitionType;
(function (AcquisitionType) {
    AcquisitionType["STARTING"] = "starting";
    AcquisitionType["TEACHER"] = "teacher";
    AcquisitionType["SHOP"] = "shop";
    AcquisitionType["QUEST_REWARD"] = "quest_reward";
    AcquisitionType["BOOK"] = "book";
    AcquisitionType["ITEM"] = "item";
    AcquisitionType["LOCATION_DISCOVERY"] = "location_discovery";
    AcquisitionType["RUNE_DISCOVERY"] = "rune_discovery";
    AcquisitionType["SPIRIT_CONTRACT"] = "spirit_contract";
    AcquisitionType["DEMON_CONTRACT"] = "demon_contract";
    AcquisitionType["ADMIN_GRANT"] = "admin_grant";
})(AcquisitionType || (exports.AcquisitionType = AcquisitionType = {}));
var SkillClassRole;
(function (SkillClassRole) {
    SkillClassRole["MASTER"] = "master";
    SkillClassRole["PROFICIENT"] = "proficient";
    SkillClassRole["NEUTRAL"] = "neutral";
    SkillClassRole["PENALIZED"] = "penalized";
    SkillClassRole["FORBIDDEN"] = "forbidden";
})(SkillClassRole || (exports.SkillClassRole = SkillClassRole = {}));
var SkillRiskType;
(function (SkillRiskType) {
    SkillRiskType["FAIL_CAST"] = "fail_cast";
    SkillRiskType["BACKFIRE_DAMAGE"] = "backfire_damage";
    SkillRiskType["SELF_STUN"] = "self_stun";
    SkillRiskType["SELF_BURN"] = "self_burn";
    SkillRiskType["BLOOD_LOSS"] = "blood_loss";
    SkillRiskType["MEMORY_LOSS"] = "memory_loss";
    SkillRiskType["SOUL_DAMAGE"] = "soul_damage";
    SkillRiskType["DEMONIC_POSSESSION"] = "demonic_possession";
    SkillRiskType["SPIRIT_ANGER"] = "spirit_anger";
    SkillRiskType["RUNE_OVERLOAD"] = "rune_overload";
    SkillRiskType["TRANSFORMATION_LOCK"] = "transformation_lock";
    SkillRiskType["FRIENDLY_FIRE"] = "friendly_fire";
    SkillRiskType["RANDOM_TARGET"] = "random_target";
})(SkillRiskType || (exports.SkillRiskType = SkillRiskType = {}));
var RiskSeverity;
(function (RiskSeverity) {
    RiskSeverity["LOW"] = "low";
    RiskSeverity["MEDIUM"] = "medium";
    RiskSeverity["HIGH"] = "high";
    RiskSeverity["EXTREME"] = "extreme";
})(RiskSeverity || (exports.RiskSeverity = RiskSeverity = {}));
var SpiritType;
(function (SpiritType) {
    SpiritType["ANCESTOR"] = "ancestor";
    SpiritType["BEAST"] = "beast";
    SpiritType["NATURE"] = "nature";
    SpiritType["FIRE"] = "fire";
    SpiritType["WATER"] = "water";
    SpiritType["EARTH"] = "earth";
    SpiritType["AIR"] = "air";
    SpiritType["SHADOW"] = "shadow";
    SpiritType["DEMON"] = "demon";
    SpiritType["UNKNOWN"] = "unknown";
})(SpiritType || (exports.SpiritType = SpiritType = {}));
var SummonType;
(function (SummonType) {
    SummonType["SPIRIT"] = "spirit";
    SummonType["DEMON"] = "demon";
    SummonType["BEAST"] = "beast";
    SummonType["UNDEAD"] = "undead";
    SummonType["ELEMENTAL"] = "elemental";
    SummonType["ILLUSION"] = "illusion";
})(SummonType || (exports.SummonType = SummonType = {}));
var SummonControlType;
(function (SummonControlType) {
    SummonControlType["DIRECT"] = "direct";
    SummonControlType["AI"] = "ai";
    SummonControlType["RISKY"] = "risky";
    SummonControlType["UNCONTROLLED"] = "uncontrolled";
})(SummonControlType || (exports.SummonControlType = SummonControlType = {}));
