"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __exportStar = (this && this.__exportStar) || function(m, exports) {
    for (var p in m) if (p !== "default" && !Object.prototype.hasOwnProperty.call(exports, p)) __createBinding(exports, m, p);
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.calculateDerivedStats = exports.calculateCharacterInitiative = exports.calculateCritChance = exports.calculateMaxDamage = exports.calculateMinDamage = exports.calculateTotalDefense = exports.validateSkillDefinition = exports.normalizeSkillResourceCosts = exports.normalizeBloodCostToHp = exports.getSkillPowerAtLevel = exports.getSkillLevelData = exports.getSkillCostSummary = exports.SummonType = exports.SummonControlType = exports.StatType = exports.SpiritType = exports.SkillType = exports.SkillTargetType = exports.SkillSubtype = exports.SkillRiskType = exports.SkillResourceType = exports.SkillClassRole = exports.SkillAreaShape = exports.RiskSeverity = exports.PhysicalDamageType = exports.MagicSchoolType = exports.HealType = exports.ElementType = exports.EffectType = exports.EffectStackMode = exports.DamageKind = exports.CastType = exports.AcquisitionType = exports.TargetZone = void 0;
__exportStar(require("./stats"), exports);
__exportStar(require("./races"), exports);
__exportStar(require("./combat"), exports);
__exportStar(require("./combat-core"), exports);
__exportStar(require("./combat-plan"), exports);
__exportStar(require("./combat-costs"), exports);
__exportStar(require("./combat-guard"), exports);
__exportStar(require("./damage"), exports);
__exportStar(require("./skills"), exports);
__exportStar(require("./arena-battle"), exports);
__exportStar(require("./arena-combat-equipment"), exports);
__exportStar(require("./combat-status-ids"), exports);
__exportStar(require("./combat-item-effect"), exports);
__exportStar(require("./combat-status-registry"), exports);
__exportStar(require("./combat-status-sync"), exports);
__exportStar(require("./combat-status-runtime"), exports);
__exportStar(require("./game-config"), exports);
__exportStar(require("./runes"), exports);
__exportStar(require("./items"), exports);
__exportStar(require("./merchants"), exports);
__exportStar(require("./inventory"), exports);
__exportStar(require("./equipment"), exports);
__exportStar(require("./shop"), exports);
__exportStar(require("./battle-map"), exports);
__exportStar(require("./progression"), exports);
var arena_battle_1 = require("./arena-battle");
Object.defineProperty(exports, "TargetZone", { enumerable: true, get: function () { return arena_battle_1.TargetZone; } });
__exportStar(require("./escape-helpers"), exports);
__exportStar(require("./escape-pipeline"), exports);
__exportStar(require("./combat-log"), exports);
var index_1 = require("./skills/index");
Object.defineProperty(exports, "AcquisitionType", { enumerable: true, get: function () { return index_1.AcquisitionType; } });
Object.defineProperty(exports, "CastType", { enumerable: true, get: function () { return index_1.CastType; } });
Object.defineProperty(exports, "DamageKind", { enumerable: true, get: function () { return index_1.DamageKind; } });
Object.defineProperty(exports, "EffectStackMode", { enumerable: true, get: function () { return index_1.EffectStackMode; } });
Object.defineProperty(exports, "EffectType", { enumerable: true, get: function () { return index_1.EffectType; } });
Object.defineProperty(exports, "ElementType", { enumerable: true, get: function () { return index_1.ElementType; } });
Object.defineProperty(exports, "HealType", { enumerable: true, get: function () { return index_1.HealType; } });
Object.defineProperty(exports, "MagicSchoolType", { enumerable: true, get: function () { return index_1.MagicSchoolType; } });
Object.defineProperty(exports, "PhysicalDamageType", { enumerable: true, get: function () { return index_1.PhysicalDamageType; } });
Object.defineProperty(exports, "RiskSeverity", { enumerable: true, get: function () { return index_1.RiskSeverity; } });
Object.defineProperty(exports, "SkillAreaShape", { enumerable: true, get: function () { return index_1.SkillAreaShape; } });
Object.defineProperty(exports, "SkillClassRole", { enumerable: true, get: function () { return index_1.SkillClassRole; } });
Object.defineProperty(exports, "SkillResourceType", { enumerable: true, get: function () { return index_1.SkillResourceType; } });
Object.defineProperty(exports, "SkillRiskType", { enumerable: true, get: function () { return index_1.SkillRiskType; } });
Object.defineProperty(exports, "SkillSubtype", { enumerable: true, get: function () { return index_1.SkillSubtype; } });
Object.defineProperty(exports, "SkillTargetType", { enumerable: true, get: function () { return index_1.SkillTargetType; } });
Object.defineProperty(exports, "SkillType", { enumerable: true, get: function () { return index_1.SkillType; } });
Object.defineProperty(exports, "SpiritType", { enumerable: true, get: function () { return index_1.SpiritType; } });
Object.defineProperty(exports, "StatType", { enumerable: true, get: function () { return index_1.StatType; } });
Object.defineProperty(exports, "SummonControlType", { enumerable: true, get: function () { return index_1.SummonControlType; } });
Object.defineProperty(exports, "SummonType", { enumerable: true, get: function () { return index_1.SummonType; } });
var index_2 = require("./skills/index");
Object.defineProperty(exports, "getSkillCostSummary", { enumerable: true, get: function () { return index_2.getSkillCostSummary; } });
Object.defineProperty(exports, "getSkillLevelData", { enumerable: true, get: function () { return index_2.getSkillLevelData; } });
Object.defineProperty(exports, "getSkillPowerAtLevel", { enumerable: true, get: function () { return index_2.getSkillPowerAtLevel; } });
Object.defineProperty(exports, "normalizeBloodCostToHp", { enumerable: true, get: function () { return index_2.normalizeBloodCostToHp; } });
Object.defineProperty(exports, "normalizeSkillResourceCosts", { enumerable: true, get: function () { return index_2.normalizeSkillResourceCosts; } });
Object.defineProperty(exports, "validateSkillDefinition", { enumerable: true, get: function () { return index_2.validateSkillDefinition; } });
var derived_stats_1 = require("./derived-stats");
Object.defineProperty(exports, "calculateTotalDefense", { enumerable: true, get: function () { return derived_stats_1.calculateTotalDefense; } });
Object.defineProperty(exports, "calculateMinDamage", { enumerable: true, get: function () { return derived_stats_1.calculateMinDamage; } });
Object.defineProperty(exports, "calculateMaxDamage", { enumerable: true, get: function () { return derived_stats_1.calculateMaxDamage; } });
Object.defineProperty(exports, "calculateCritChance", { enumerable: true, get: function () { return derived_stats_1.calculateCritChance; } });
Object.defineProperty(exports, "calculateCharacterInitiative", { enumerable: true, get: function () { return derived_stats_1.calculateInitiative; } });
Object.defineProperty(exports, "calculateDerivedStats", { enumerable: true, get: function () { return derived_stats_1.calculateDerivedStats; } });
