export const ITEMS = {
    iron_sword: {
        id: 'iron_sword',
        name: 'Iron Sword',
        itemType: 'weapon',
        itemSubType: 'sword',
        price: 140,
        requiredStats: { strength: 6 },
        bonuses: { strength: 2 },
        stackable: false,
        description: 'Надежный меч для ближнего боя.',
        icon: 'sword',
        rarity: 'common',
    },
    raider_axe: {
        id: 'raider_axe',
        name: 'Raider Axe',
        itemType: 'weapon',
        itemSubType: 'axe',
        price: 180,
        requiredStats: { strength: 7 },
        bonuses: { strength: 3, perception: -1 },
        stackable: false,
        description: 'Тяжелый топор с высоким уроном.',
        icon: 'axe',
        rarity: 'uncommon',
    },
    hunter_bow: {
        id: 'hunter_bow',
        name: 'Hunter Bow',
        itemType: 'weapon',
        itemSubType: 'bow',
        price: 170,
        requiredStats: { dexterity: 7 },
        bonuses: { dexterity: 2, perception: 1 },
        stackable: false,
        description: 'Легкий лук для точных ударов.',
        icon: 'bow',
        rarity: 'common',
    },
    initiate_staff: {
        id: 'initiate_staff',
        name: 'Initiate Staff',
        itemType: 'weapon',
        itemSubType: 'staff',
        price: 160,
        requiredStats: { intelligence: 7 },
        bonuses: { intelligence: 2, willpower: 1 },
        stackable: false,
        description: 'Базовый посох для практики магии.',
        icon: 'staff',
        rarity: 'common',
    },
    ash_longbow: {
        id: 'ash_longbow',
        name: 'Ash Longbow',
        itemType: 'weapon',
        itemSubType: 'bow',
        price: 240,
        requiredStats: { dexterity: 9 },
        bonuses: { dexterity: 3, perception: 1 },
        stackable: false,
        description: 'Дальнобойный лук с высокой точностью.',
        icon: 'bow',
        rarity: 'uncommon',
    },
    steel_spear: {
        id: 'steel_spear',
        name: 'Steel Spear',
        itemType: 'weapon',
        itemSubType: 'spear',
        price: 210,
        requiredStats: { strength: 7, dexterity: 6 },
        bonuses: { strength: 2, dexterity: 1 },
        stackable: false,
        description: 'Копье для контроля дистанции.',
        icon: 'spear',
        rarity: 'uncommon',
    },
    war_hammer: {
        id: 'war_hammer',
        name: 'War Hammer',
        itemType: 'weapon',
        itemSubType: 'hammer',
        price: 260,
        requiredStats: { strength: 10 },
        bonuses: { strength: 4, perception: -1 },
        stackable: false,
        description: 'Молот с сильным пробивающим ударом.',
        icon: 'hammer',
        rarity: 'rare',
    },
    twin_daggers: {
        id: 'twin_daggers',
        name: 'Twin Daggers',
        itemType: 'weapon',
        itemSubType: 'daggers',
        price: 200,
        requiredStats: { dexterity: 8 },
        bonuses: { dexterity: 3, perception: 1 },
        stackable: false,
        description: 'Парные кинжалы для быстрых серий ударов.',
        icon: 'dagger',
        rarity: 'uncommon',
    },
    knight_blade: {
        id: 'knight_blade',
        name: 'Knight Blade',
        itemType: 'weapon',
        itemSubType: 'sword',
        price: 290,
        requiredStats: { strength: 9, constitution: 6 },
        bonuses: { strength: 3, constitution: 1, perception: 1 },
        stackable: false,
        description: 'Клинок городской стражи для уверенного фронтального боя.',
        icon: 'sword',
        rarity: 'rare',
    },
    bonebreaker_maul: {
        id: 'bonebreaker_maul',
        name: 'Bonebreaker Maul',
        itemType: 'weapon',
        itemSubType: 'hammer',
        price: 320,
        requiredStats: { strength: 11 },
        bonuses: { strength: 5, perception: -1 },
        stackable: false,
        description: 'Тяжелая кувалда для проламывания строя и щитов.',
        icon: 'hammer',
        rarity: 'rare',
    },
    ranger_shortbow: {
        id: 'ranger_shortbow',
        name: 'Ranger Shortbow',
        itemType: 'weapon',
        itemSubType: 'bow',
        price: 230,
        requiredStats: { dexterity: 8, perception: 6 },
        bonuses: { dexterity: 2, perception: 2 },
        stackable: false,
        description: 'Лук разведчика для быстрого маневренного боя.',
        icon: 'bow',
        rarity: 'uncommon',
    },
    battlemage_rod: {
        id: 'battlemage_rod',
        name: 'Battlemage Rod',
        itemType: 'weapon',
        itemSubType: 'staff',
        price: 280,
        requiredStats: { intelligence: 9, willpower: 6 },
        bonuses: { intelligence: 3, willpower: 2 },
        stackable: false,
        description: 'Жезл боевого мага, усиливающий урон и контроль.',
        icon: 'staff',
        rarity: 'rare',
    },
    leather_helmet: {
        id: 'leather_helmet',
        name: 'Leather Helmet',
        itemType: 'helmet',
        itemSubType: 'light',
        price: 90,
        requiredStats: { constitution: 4 },
        bonuses: { constitution: 1 },
        stackable: false,
        description: 'Простой шлем для защиты головы.',
        icon: 'helmet',
        rarity: 'common',
    },
    plated_helm: {
        id: 'plated_helm',
        name: 'Plated Helm',
        itemType: 'helmet',
        itemSubType: 'heavy',
        price: 170,
        requiredStats: { constitution: 7 },
        bonuses: { constitution: 2, hp: 10 },
        stackable: false,
        description: 'Закрытый шлем для тех, кто держит линию.',
        icon: 'helmet',
        rarity: 'uncommon',
    },
    chain_armor: {
        id: 'chain_armor',
        name: 'Chain Armor',
        itemType: 'armor',
        itemSubType: 'medium',
        price: 220,
        requiredStats: { constitution: 6 },
        bonuses: { constitution: 2, hp: 10 },
        stackable: false,
        description: 'Кольчужный доспех для арены.',
        icon: 'armor',
        rarity: 'uncommon',
    },
    brigandine_armor: {
        id: 'brigandine_armor',
        name: 'Brigandine Armor',
        itemType: 'armor',
        itemSubType: 'medium',
        price: 300,
        requiredStats: { constitution: 8, strength: 6 },
        bonuses: { constitution: 3, hp: 20, stamina: 10 },
        stackable: false,
        description: 'Плотная бригантина для аренных ветеранов.',
        icon: 'armor',
        rarity: 'rare',
    },
    traveler_boots: {
        id: 'traveler_boots',
        name: 'Traveler Boots',
        itemType: 'boots',
        itemSubType: 'light',
        price: 110,
        requiredStats: { dexterity: 5 },
        bonuses: { dexterity: 1, perception: 1 },
        stackable: false,
        description: 'Сапоги для мобильного боя.',
        icon: 'boots',
        rarity: 'common',
    },
    scout_boots: {
        id: 'scout_boots',
        name: 'Scout Boots',
        itemType: 'boots',
        itemSubType: 'light',
        price: 165,
        requiredStats: { dexterity: 6 },
        bonuses: { dexterity: 2, perception: 1, stamina: 10 },
        stackable: false,
        description: 'Сапоги для обхода фланга и резких смещений.',
        icon: 'boots',
        rarity: 'uncommon',
    },
    iron_gloves: {
        id: 'iron_gloves',
        name: 'Iron Gloves',
        itemType: 'gloves',
        itemSubType: 'combat',
        price: 100,
        requiredStats: { strength: 5 },
        bonuses: { strength: 1, dexterity: 1 },
        stackable: false,
        description: 'Перчатки для надежного хвата.',
        icon: 'gloves',
        rarity: 'common',
    },
    duelist_gloves: {
        id: 'duelist_gloves',
        name: 'Duelist Gloves',
        itemType: 'gloves',
        itemSubType: 'precision',
        price: 155,
        requiredStats: { dexterity: 6 },
        bonuses: { dexterity: 2, perception: 1 },
        stackable: false,
        description: 'Тонкие перчатки для быстрых точных выпадов.',
        icon: 'gloves',
        rarity: 'uncommon',
    },
    tower_shield: {
        id: 'tower_shield',
        name: 'Tower Shield',
        itemType: 'shield',
        itemSubType: 'heavy',
        price: 190,
        requiredStats: { constitution: 7 },
        bonuses: { constitution: 3, perception: -1 },
        stackable: false,
        description: 'Большой щит для устойчивости.',
        icon: 'shield',
        rarity: 'uncommon',
    },
    kite_shield: {
        id: 'kite_shield',
        name: 'Kite Shield',
        itemType: 'shield',
        itemSubType: 'balanced',
        price: 240,
        requiredStats: { constitution: 6, strength: 5 },
        bonuses: { constitution: 2, willpower: 1, stamina: 10 },
        stackable: false,
        description: 'Универсальный щит для гибкой обороны.',
        icon: 'shield',
        rarity: 'uncommon',
    },
    potion_hp_small: {
        id: 'potion_hp_small',
        name: 'Small HP Potion',
        itemType: 'consumable',
        itemSubType: 'potion_hp',
        price: 45,
        requiredStats: {},
        bonuses: {},
        stackable: true,
        description: 'Восстанавливает здоровье в бою.',
        icon: 'potion_hp',
        rarity: 'common',
    },
    potion_mp_small: {
        id: 'potion_mp_small',
        name: 'Small MP Potion',
        itemType: 'consumable',
        itemSubType: 'potion_mp',
        price: 50,
        requiredStats: {},
        bonuses: {},
        stackable: true,
        description: 'Восстанавливает ману в бою.',
        icon: 'potion_mp',
        rarity: 'common',
    },
    tonic_focus: {
        id: 'tonic_focus',
        name: 'Focus Tonic',
        itemType: 'consumable',
        itemSubType: 'buff',
        price: 85,
        requiredStats: {},
        bonuses: {},
        stackable: true,
        description: 'Простой баф точности для арены.',
        icon: 'buff_focus',
        rarity: 'uncommon',
    },
    tonic_ironhide: {
        id: 'tonic_ironhide',
        name: 'Ironhide Tonic',
        itemType: 'consumable',
        itemSubType: 'buff',
        price: 110,
        requiredStats: {},
        bonuses: {},
        stackable: true,
        description: 'Тоник для устойчивости в тяжелом бою.',
        icon: 'buff_guard',
        rarity: 'uncommon',
    },
    potion_stamina_large: {
        id: 'potion_stamina_large',
        name: 'Large Stamina Draught',
        itemType: 'consumable',
        itemSubType: 'buff',
        price: 120,
        requiredStats: {},
        bonuses: {},
        stackable: true,
        description: 'Восстанавливает запас сил для следующего обмена ударами.',
        icon: 'buff_focus',
        rarity: 'rare',
    },
};
export function getItemById(itemId) {
    const item = ITEMS[itemId];
    if (!item) {
        throw new Error(`Unknown item id: ${itemId}`);
    }
    return item;
}
