import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
export const FighterListColumn = ({ fighters, selectedFighterId, onFighterSelect, isEnemySide = false, }) => {
    const getHealthPercentage = (current, max) => {
        return Math.max(0, Math.min(100, (current / max) * 100));
    };
    const getManaPercentage = (current, max) => {
        return Math.max(0, Math.min(100, (current / max) * 100));
    };
    return (_jsxs("div", { className: `battle-${isEnemySide ? 'right' : 'left'}-column`, children: [_jsxs("div", { className: "battle-column-header", children: [_jsx("h3", { children: isEnemySide ? 'Enemies' : 'Allies' }), _jsxs("div", { className: "round-info", children: [fighters.length, " active"] })] }), _jsx("div", { className: "fighter-list-container", children: fighters.map((fighter) => (_jsxs("div", { className: `fullscreen-fighter-card ${selectedFighterId === fighter.id ? 'is-selected' : ''} ${fighter.currentHp <= 0 ? 'is-dead' : ''}`, onClick: () => onFighterSelect(fighter.id), children: [_jsx("div", { className: "fullscreen-fighter-avatar", children: fighter.name.charAt(0).toUpperCase() }), _jsxs("div", { className: "fullscreen-fighter-info", children: [_jsxs("div", { className: "fullscreen-fighter-name", children: [_jsx("strong", { children: fighter.name }), _jsx("span", { className: `state-badge ${fighter.currentHp > 0 ? 'alive' : 'dead'}`, children: fighter.currentHp > 0 ? 'Alive' : 'Dead' })] }), _jsxs("div", { className: "fullscreen-fighter-bars", children: [_jsxs("div", { className: "fullscreen-bar-row", children: [_jsxs("div", { className: "fullscreen-bar-label", children: [_jsx("span", { children: "HP" }), _jsxs("span", { children: [fighter.currentHp, " / ", fighter.maxHp] })] }), _jsx("div", { className: "fullscreen-meter hp", children: _jsx("span", { style: { width: `${getHealthPercentage(fighter.currentHp, fighter.maxHp)}%` } }) })] }), fighter.currentMp > 0 && (_jsxs("div", { className: "fullscreen-bar-row", children: [_jsxs("div", { className: "fullscreen-bar-label", children: [_jsx("span", { children: "Mana" }), _jsxs("span", { children: [fighter.currentMp, " / ", fighter.maxMp || 0] })] }), _jsx("div", { className: "fullscreen-meter mana", children: _jsx("span", { style: { width: `${getManaPercentage(fighter.currentMp, fighter.maxMp || 1)}%` } }) })] }))] })] })] }, fighter.id))) }), fighters.length === 0 && (_jsx("div", { style: { padding: '16px', textAlign: 'center', color: 'var(--text-muted)' }, children: "No fighters active" }))] }));
};
